# Generated by Django 5.0.7 on 2024-09-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('Car_Model', models.CharField(max_length=100)),
                ('car_Price', models.IntegerField(max_length=15)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='carPhoto/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Cars.cars_data')),
            ],
        ),
    ]
