# Generated by Django 5.0.7 on 2024-09-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_details',
            name='car_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='cars_data',
        ),
    ]
